//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SURVEY
    {
        public TBL_SURVEY()
        {
            this.TBL_QUESTIONSANSWERS = new HashSet<TBL_QUESTIONSANSWERS>();
            this.TBL_SURVEYQUESTIONS = new HashSet<TBL_SURVEYQUESTIONS>();
            this.TBL_USERSRESPONSE = new HashSet<TBL_USERSRESPONSE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UsersID { get; set; }
        public string SurveyName { get; set; }
    
        public virtual ICollection<TBL_QUESTIONSANSWERS> TBL_QUESTIONSANSWERS { get; set; }
        public virtual TBL_USERS TBL_USERS { get; set; }
        public virtual ICollection<TBL_SURVEYQUESTIONS> TBL_SURVEYQUESTIONS { get; set; }
        public virtual ICollection<TBL_USERSRESPONSE> TBL_USERSRESPONSE { get; set; }
    }
}
