//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SURVEYQUESTIONS
    {
        public TBL_SURVEYQUESTIONS()
        {
            this.TBL_QUESTIONSANSWERS = new HashSet<TBL_QUESTIONSANSWERS>();
            this.TBL_USERSRESPONSE = new HashSet<TBL_USERSRESPONSE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public string Questions { get; set; }
    
        public virtual ICollection<TBL_QUESTIONSANSWERS> TBL_QUESTIONSANSWERS { get; set; }
        public virtual TBL_SURVEY TBL_SURVEY { get; set; }
        public virtual ICollection<TBL_USERSRESPONSE> TBL_USERSRESPONSE { get; set; }
    }
}
